action_num: 8
agent: pg
chi: 1.0
deterministic_ratio_list:
- 1.0
- 0.7
- 1.0
dpo_ada_coef: 1.0
dpo_adaptive: false
dpo_num_iters: 100
dpo_step_size: 0.1
dpo_type: dpo
env: group_linear_bandit
eval_metric: argmax
eval_metric_prob: KL
exp_adaptive: 0.0
feature_type: swapped
group_num: 3
importance_sampling: false
importance_sampling_weights: None
ipo_grad_type: linear
l2_reg_rdpo: 0.0
lamba: 0.0
log_dir: log_dpo/2024_09_18_13_54_54/swapped_noise0.7_[1,0.7,1]_2022
mle_ada_coef: 1.0
mle_adaptive: true
mle_num_iters: 100
mle_step_size: 0.1
num_trials_for_eval: 1000
param_limit: 5
pref_data_num: 300
rdpo_adj: '0'
rdpo_batch_size: 300
rdpo_exp_step_size: 0.01
rdpo_weighted_batches: false
reg_coef: 0.1
seed: 2022
state_dim: 2
test_weights: '[1,1,1]'
use_closed_form: true
use_theory: true
use_uneven_grp: true
use_uneven_grp_val: true
use_weight_val: false
val_data_num: 50
val_deterministic: true
val_deterministic_ratio_list:
- 1.0
- 0.7
- 1.0
val_weights: '[1,1,1]'
wandb_entity: group-robustness-noisy-labels
wandb_group: group_3_exp
wandb_key: fbf79a31d3c4d52eaf326308d880d3ebca26b10d
wandb_logdir: log_dpo/2024_09_18_13_54_54/swapped_noise0.7_[1,0.7,1]_2022/log
wandb_name: dpo,0.1,0.1,0.01,[1,0.7,1],2022
wandb_project: common-good-ipo
wandb_use: true
weights: '[1,1,1]'
