action_num: 8
agent: pg
chi: 1.0
deterministic_ratio_list:
- 1.0
- 0.8
- 1.0
dpo_ada_coef: 1.0
dpo_adaptive: false
dpo_num_iters: 100
dpo_step_size: 0.2
dpo_type: rdpo
env: group_linear_bandit
eval_metric: argmax
eval_metric_prob: KL
exp_adaptive: 0.0
feature_type: flipped
group_num: 3
importance_sampling: false
importance_sampling_weights: None
ipo_grad_type: linear
l2_reg_rdpo: 0.0
lamba: 0.0
log_dir: log-hyperparam-search/2024_10_07_17_04_32/rdpo,0.2,0.1,1,2022
mle_ada_coef: 1.0
mle_adaptive: true
mle_num_iters: 100
mle_step_size: 0.1
num_trials_for_eval: 1000
param_limit: 5
pref_data_num: 300
rdpo_adj: '0'
rdpo_batch_size: 300
rdpo_exp_step_size: 1.0
rdpo_weighted_batches: false
reg_coef: 0.1
seed: 2022
state_dim: 2
test_weights: equal
use_closed_form: true
use_theory: false
use_uneven_grp: false
use_uneven_grp_val: false
use_weight_val: false
val_data_num: 50
val_deterministic: true
val_deterministic_ratio_list:
- 1.0
- 1.0
- 1.0
val_weights: equal
wandb_entity: group-robustness-noisy-labels
wandb_group: group1
wandb_key: fbf79a31d3c4d52eaf326308d880d3ebca26b10d
wandb_logdir: log-hyperparam-search/2024_10_07_17_04_32/rdpo,0.2,0.1,1,2022/log
wandb_name: rdpo,0.2,0.1,1
wandb_project: hp-search
wandb_use: true
weights: '[1,1,0.4]'
